name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v4.2.0
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'      
        with:
          cmd: install
      - uses: borales/actions-yarn@v4.2.0
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'      
        with:
          cmd: test
