name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
      - uses: borales/actions-yarn@v3
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'      
        with:
          cmd: install
      - uses: borales/actions-yarn@v3
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'      
        with:
          cmd: test
